[package]
authors = ["Terkwood <38859656+Terkwood@users.noreply.github.com>"]
description = "mood tracking web application"
edition = "2018"
name = "equanimity"
version = "0.5.5-a"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chrono = "0.4.15"
js-sys = "0.3.44"
serde = "1.0.115"
serde_derive = "1.0.115"
serde_json = "1.0.57"
wasm-bindgen = "0.2.67"
web-sys = {version = "0.3.44", features = ["Window", "Storage"]}
yew = "0.17.3"
